@startuml
title "Klassendiagramm"

rectangle System {
    package Training {
        package "Programm Auswahl" {
            class Program {
                + List<TrainingsDay> days
            }

            class TrainingsDay {
                + List<Übungen> übungen
            }

            class AvailablePrograms {
                + List<Program> programms
                + select(int index): Program
            }
        }

        package Trainingskontrolle {
            class Training {
                - Program program
                + start(): void
                + stop(): void
                + setProgram(Program): void
                + startNextExercise(): void
            }

            package Timer {
                interface Timer {}
                class CountdownTimer implements Timer {}
            }
        }

        ' package "Programm Erstellung" {}
    }

    ' package Fortschritt {}

    package Übungen {
        class Übung {
            + getDiscription(): String
        }
    }
}


Training --> Timer
Training -> AvailablePrograms
AvailablePrograms *- Program
TrainingsDay *-- Übung
Program *- TrainingsDay

@enduml